version: '3.0'

services:
  widget:
    image: garystafford/microservice-docker-demo-widget:latest
    hostname: widget
    depends_on:
    - mongodb
    ports:
    - 8030:8030/tcp
    networks:
    - widget_overlay_net
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}
        fluentd-address: localhost:24224
        labels: environment=development
        env: environment=development
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
        - node.hostname != worker3
    environment:
    - "CONSUL_SERVER_URL=${CONSUL_SERVER}"
    - "SERVICE_NAME=widget"
    - "SERVICE_TAGS=service"
    command: "java -Dspring.profiles.active=${WIDGET_PROFILE} \
      -Djava.security.egd=file:/dev/./urandom \
      -jar widget/widget-service.jar"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    command:
    - --smallfiles
    ports:
    - 27017:27017/tcp
    networks:
    - widget_overlay_net
    volumes:
    - widget_data_vol:/data/db
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}
        fluentd-address: localhost:24224
        labels: environment=development
        env: environment=development
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == worker
        - node.hostname != worker3
    environment:
    - "SERVICE_NAME=mongodb"
    - "SERVICE_TAGS=database"

networks:
  widget_overlay_net:
    external: true

volumes:
  widget_data_vol:
    external: true
